WIP2

diff --git a/openldap/imageroot/actions/provision-domain/10expand_templates b/openldap/imageroot/actions/provision-domain/10expand_templates
--- a/openldap/imageroot/actions/provision-domain/10expand_templates
+++ b/openldap/imageroot/actions/provision-domain/10expand_templates
@@ -20,10 +20,30 @@
 # along with NethServer.  If not, see COPYING.
 #
 
-set -e
-echo '{}' # Satisfy validate-output.json schema
-
 exec 1>&2
+set -e
 
-# Enable and start the service
-systemctl --user enable --now openldap.service
+export FIRST_DOMAIN_COMPONENT=${DOMAIN/.*/}
+
+mkdir -p ~/ldifs
+
+envsubst >~/ldifs/20_config.ldif <${AGENT_INSTALL_DIR}/config.ldif.template
+envsubst >~/ldifs/30_dit.ldif <${AGENT_INSTALL_DIR}/dit.ldif.template
+
+# TODO syncrepl configuration
+
+# dn: olcDatabase={2}mdb,cn=config
+# changetype:modify
+# replace: olcSyncrepl
+# olcSyncrepl: rid=001
+#   provider=ldap://10.5.4.1:20001
+#   binddn="cn=admin,dc=dp,dc=nethserver,dc=net"
+#   bindmethod=simple
+#   credentials=Nethesis,1234
+#   searchbase="dc=dp,dc=nethserver,dc=net"
+#   type=refreshAndPersist
+#   retry="5 5 300 +"
+#   timeout=5
+# -
+# replace: olcMirrorMode
+# olcMirrorMode: TRUE
